# TODO (Avnishn): compute metrics in class
INTER_TOKEN_LAT = "inter_token_latency_s"
TTFT = "ttft_s"
E2E_LAT = "end_to_end_latency_s"
NUM_INPUT_TOKENS = "number_input_tokens"
NUM_OUTPUT_TOKENS = "number_output_tokens"
NUM_TOTAL_TOKENS = "number_total_tokens"
REQ_OUTPUT_THROUGHPUT = "request_output_throughput_token_per_s"
ERROR_MSG = "error_msg"
ERROR_CODE = "error_code"
ERROR_CODE_FREQ = "error_code_frequency"
NUM_ERRORS = "number_errors"
OUTPUT_THROUGHPUT = "mean_output_throughput_token_per_s"
NUM_COMPLETED_REQUESTS = "num_completed_requests"
COMPLETED_REQUESTS_PER_MIN = "num_completed_requests_per_min"
ERROR_RATE = "error_rate"
NUM_REQ_STARTED = "num_requests_started"

# Structured output and tool calling metrics
JSON_VALID = "json_valid"
JSON_SCHEMA_VALID = "json_schema_valid"
JSON_PARSE_ERROR = "json_parse_error"
SCHEMA_VALIDATION_ERROR = "schema_validation_error"
TOOL_CALL_SUCCESS = "tool_call_success"
TOOL_CALL_ERROR = "tool_call_error"
NUM_TOOL_CALLS = "number_tool_calls"
TOOL_CALL_ACCURACY = "tool_call_accuracy"
STRUCTURED_OUTPUT_ACCURACY = "structured_output_accuracy"
RESPONSE_FORMAT_COMPLIANCE = "response_format_compliance"

# Accuracy and validation metrics
ACCURACY_SCORE = "accuracy_score"
VALIDATION_ERRORS = "validation_errors"
EXPECTED_VS_ACTUAL = "expected_vs_actual"
SEMANTIC_SIMILARITY = "semantic_similarity"
